### PR TITLE
Update azure Key Vault Keys, Secrets, Certificates SDK to T2

### PR DESCRIPTION
**Pull request by JosueJoshua**
**SDK Update List**
1. azure-keyvault -> @azure/keyvault-keys、@azure/keyvault-secrets、@azure/keyvault-certificates

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@sadasant, Please review the changes here

**Comment by sadasant** [comment]
Hi again! This might be obvious, but with the intention of saving some time:

- Please add `dotenv`, `@azure/keyvault-keys`, `@azure/keyvault-secrets`, and `@azure/keyvault-certificates` to the `package.json`.
- Please update the `package-lock.json`.
- For the credentials, this could go in a separate PR, but the readme doesn't include what credentials one needs to have in order to run this on the Key Vault, or even at the resource group level. That could help a lot, specially to new users!

Please let me know if any of this is confusing, we could even go through this together and I'm sure we'll be able to come up with something nice.

**Comment by sadasant** [comment]
More feedback:

- The `README` needs information about the environment variable `AZURE_RESOURCE_GROUP`, I believe.
- I keep getting that the application I'm using `does not have keys create permission on key vault`, meaning that the permissions aren't properly set once the Key Vaults are created.
- The Key Vaults created aren't automatically deleted (if this is expected, then feel free to ignore this point).

**Comment by JosueJoshua** [comment]
@sadasant 
The permission are related to Key Vault Management, and we plan to make corresponding changes after the Key Vault Management is updated.

**Comment by JosueJoshua** [comment]
@sadasant 
- The environment variable AZURE_RESOURCE_GROUP added to the README.
- The permission are related to Key Vault Management, and we plan to make corresponding changes after the Key Vault Management is updated.

**Pull request merged**
